### ISSUE TITLE
source code update missed? 

### ISSUE THREAD

**Issue by tmhm** [modriczhang/HRL-Rec#2]
Hi, guys, I came here from the paper `HRL-Rec`, and was very interested in your works on applying hierarchical reinforcement learning to recommendation scenarios,  but found an empty repo here, when will you guys update it ? 🔢 : )

**Comment by modriczhang** [comment]
I will release an update in the next few days.

**Comment by tmhm** [comment]
Cool! 👍

**Comment by tmhm** [comment]
> I will release an update in the next few days.

**Comment by weberrr** [comment]
@modriczhang when will you guys update it ?

**Comment by wenl-li** [comment]
Looking forward to your update

**Comment by modriczhang** [comment]
released
